version: '3.8'

services:
  task-tracker:
    build: .
    container_name: task-tracker
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null  # Keeps the container running
